name: Build & Deploy Flappy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Emscripten cache path
        run: |
          echo "EM_CACHE=/home/runner/.emscripten_cache" >> $GITHUB_ENV

      - name: Cache Emscripten ports
        uses: actions/cache@v4
        with:
          path: /home/runner/.emscripten_cache
          key: emscripten-ports-${{ runner.os }}

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - name: Build with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          emcc main.c \
          -o index.html \
          -s USE_SDL=2 \
          -s USE_SDL_IMAGE=2 \
          -s USE_SDL_TTF=2 \
          -lidbfs.js \
          -s SDL2_IMAGE_FORMATS='["png","jpg"]' \
          -s ALLOW_MEMORY_GROWTH=1 \
          -g -fsanitize=address \
          --preload-file assets@assets \
          --use-preload-cache \
          -O2

      - name: Show files
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
          keep_files: false